# before_script:
#   - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY

services:
  - docker:dind

docker_build:
  stage: build
  image: docker:latest
  script:
    - docker build --tag repo.kk.int/3d-bot .

# deploy-prod:
#   stage: deploy
#   script:
#     - docker stack deploy -c docker-compose.yml --with-registry-auth my-stack
#   only:
#     - master
