# before_script:
#   - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY

image: docker:dind

variables:
  DOCKER_TLS_CERTDIR: "/certs"

services:
  - name: docker:dind
    command: ["--registry-mirror", "https://mirror.kk.int"]

docker_build:
  stage: build
  image: docker:latest
  script:
    - docker build --tag repo.kk.int/3d-bot .

# deploy-prod:
#   stage: deploy
#   script:
#     - docker stack deploy -c docker-compose.yml --with-registry-auth my-stack
#   only:
#     - master
