variables:
  DOCKER_DRIVER: overlay2
  # DOCKER_TLS_CERTDIR: ""

stages:
  - build
  - deploy

build_production:
  stage: build
  only:
  - main
  image: repo.kk.int/runner-dind:latest
  
  before_script:
    - docker login -u${NEXUS_CI_USER} -p${NEXUS_CI_PASSWORD} ${NEXUS_REPO_HOST}
  after_script:
    - docker buildx rm ${CI_PROJECT_NAME}-builder
    - docker logout ${NEXUS_REPO_HOST}
  script:
    - echo "building ${CI_PROJECT_NAME} for ${PROJECT_PLATTFORMS}"
    - docker buildx create 
      --name builder-${CI_PROJECT_NAME}
      --driver docker-container
      --config /etc/buildkit.toml 
      --use
    - docker buildx inspect --bootstrap
    - docker buildx build 
      --platform ${PROJECT_PLATTFORMS}
      --no-cache
      --push
      -f ${CI_PROJECT_DIR}/Dockerfile 
      --tag ${NEXUS_REPO_HOST}/${CI_PROJECT_NAME}:${CI_COMMIT_SHORT_SHA}
      --tag ${NEXUS_REPO_HOST}/${CI_PROJECT_NAME}:latest . 

deploy:
  stage: deploy
  only:
    - main
  image: alpine
  before_script:
    - apk add openssh
    - 'command -v ssh-agent >/dev/null || ( apk add --update openssh )' 
    - eval $(ssh-agent -s)
    - echo "${SSH_PRIVATE_KEY}" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan ${SWARM_MANAGER} >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script:
    - ssh
      ${SWARM_MANAGER_USER}@${SWARM_MANAGER} 
      "cd /mnt/clusterfs && 
      docker service update 
      --force 
      --update-failure-action rollback 
      --image ${NEXUS_REPO_HOST}/${CI_PROJECT_NAME}:latest
      botfarm_${CI_PROJECT_NAME}"

