kind: Secret
apiVersion: v1
metadata:
    name: 3d-bot-secret
    namespace: 3d-bot
type: Opaque
data:
    octopi_key: ENC[AES256_GCM,data:zaif2csraMTqTmOd0og8+jo04/L3wLVe+R7+1bpNcZKUaYASNlHZ5d1WE7Q=,iv:+kwfwJQ55dbrFgMsoR1PMOOvN72br0BomwP8J0izCHU=,tag:2mhFHH59HdoDlQ0nV1Va9A==,type:str]
    telegram_api_key: ENC[AES256_GCM,data:O2TbcEbQsT8A5b6dc95jKKobiMjxsb3j2UO/wWQSiex81OElX5f8ILKe9EfjN/jSbfJrNR7fJJh/5dCXGQ42QQ==,iv:WQnM5DWKK+AAQBZ70Ae2BZhl8AlKfUL5Yxt1pv6j62g=,tag:ebH1Qnxi3BjjV/bxBF4Znw==,type:str]
    telegram_chat_id: ENC[AES256_GCM,data:rDs5AmRipN2EWW5zMGfgKw==,iv:xDsOoL9ZiIns2FrppuciHROSXqIT5M045vO3jm58XPY=,tag:LBhAUbbOedQxUfzoE/p1tg==,type:str]
    mqtt_user: ENC[AES256_GCM,data:Kz2x1Q==,iv:QQ0j5lc0907fhyNg2PuG8plKnJ/Vkw5q8k6Q1rBZ/wQ=,tag:L1+f1KtOUj/yf7QDs0JKvQ==,type:str]
    mqtt_password: ENC[AES256_GCM,data:xNBJUSA/B4rAjMDbqBW7svK7qMgN3GH2,iv:6/uhz84kAjbq8LHeiRYPCwM9rOQm/eVT29lo0T95cmI=,tag:tlDsUpqYfZR8fFlGjeIgqw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1t9jj8nxxg5fuxwft4pcwh5xnmc3x84fy6cmrcq9u33pq7pc3u5kqnewfru
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQR2k4bFhJMVhLdW5GWG1M
            OWFRdjNqdEo0OGRJRmg3TWhiUHFqd0Z2L3hjCnR5akFHZ3VzM0N2dEpGaitzTGFB
            QjNUQUpkYlJ6VjU4Zmx2cit2Y011dWcKLS0tIEZhbHQ4eTZXN01SVXdFVU9KZGF6
            VXBlUkJQN2Y4d1laM3QybE5zNnlYS2cKpKCORkhv9lTDRXYVqUk5fMmqdFe2AHFx
            qyCagi/QkdqYDfYo6obymPhXR3xJ1abJIPsnOrhA3yeit6ceuhIsgg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-23T17:52:18Z"
    mac: ENC[AES256_GCM,data:QSfc9qyQZuFLMEu+ohoBLUZM6HGwC5GNoruY/mqliGW7pC9oophcyK3trRIbHvAa+TyASlhpwkBPgQXtfDVgUihT8i9lTRljtLzSP8JEqQN8osIWbNXj6eayj/9MUk2bNx3+OcaNFNA+RDx8kbjT9RQt2pWDpYMd3QZdQE8zL6A=,iv:JdBgTF2SqCQtOM2Ttn78Y/pb41i3qoXulQTko+bwscg=,tag:TxXFYT1or5V07YyfnvwzjQ==,type:str]
    pgp: []
    encrypted_regex: ^(data)$
    version: 3.7.3
