kind: Secret
apiVersion: v1
metadata:
    name: 3d-bot-secret
    namespace: 3d-bot
type: Opaque
data:
    octopi_key: NDgwQUM4NjVFRTY1NDE4NEE1MTQ0RDQ5QzBEOUQyREU=
    telegram_api_key: MTE0NDE4ODQ5NzpBQUdCalkzVDdXbVdjTGRoYmVvS3lCdEY1cXRhNE9OSXpOMA==
    telegram_chat_id: LTczMTY0OTI3Mw==
    mqtt_user: aW90
    mqtt_password: VmFpeWFldG9yb3NoMlF1YQ==
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1t9jj8nxxg5fuxwft4pcwh5xnmc3x84fy6cmrcq9u33pq7pc3u5kqnewfru
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByTjA1aXNBZ21XWVk0NURB
            ZDZsa0owcXNsZDhYdCtwdWU1TG9PbXZMREVJClpMNTZYc2ZmWjl3STlvaU5LTXpr
            cjJPaUo2ME1mdUNDQWl2Mng5dmpsK2MKLS0tIHovc0IreUJtQW1CLzMxeFBkdjFo
            MlY3L0tnc1d0b2UvMCt6dWxvdDZLSmcKgPFCrCJy2hpcl4xLzF0w4Us0B4Y6MrE6
            ZbPzxVH0ltBPpKnpGpKgZm5EM5njg1VxfyHlyvFj8Ldc0XqUPKw+WA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-24T17:13:02Z"
    mac: ENC[AES256_GCM,data:kE3/mcsXVf9SL5DZPnVuFgNB0LpJAKZGj4iIoYXQ5s4+MnHx9W2gSPcr76/lQXfwOKhNuTitU4b/CcIxnoK/uBYBreyD44YPA3v62KQBz2AXeyMy4BNFnvnLLn7tNLy0AgJ7bQBDap4/jBEN/twiH4OMVozNH1D68z1a1bi2L2M=,iv:39k4StY9ToiAmH2DEeKLFMoDBnD8yBD3onjzJPOWmjs=,tag:5yLd/zR09MXQi+cgPi1FcA==,type:str]
    pgp: []
    encrypted_suffix: secretTemplates
    version: 3.7.3
